name: Test Workflow

on:
    push:
        branches:
            - dev

jobs:
    test:
        runs-on: ubuntu-latest

        steps:

            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Run Command
              run: npm ci

            - name: Docker Build
              run: |
                docker build \
                -t node-app:latest \
                -t node-app:${{ github.sha }} \
                .

            - name: Print Docker Images
              run: docker images