name: Test Workflow

on:
    push:
        branches:
            - dev

jobs:
    test:
        runs-on: ubuntu-latest

        steps:

            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Run Command
              run: |
                pwd
                ls -la
                node --version

              