name: Test Workflow

on:
    push:
        branches:
            - dev

jobs:
    build:
        runs-on: ubuntu-latest

        steps:

            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Run Command
              run: npm ci

            - name: Docker Build
              run: |
                docker build \
                -t node-app:latest \
                -t node-app:${{ github.sha }} \
                .

            - name: Print Docker Images
              run: docker images
    
    deploy:
      needs: build
      runs-on: ubuntu-latest

      steps:

        - name: Login to EC2 using appleboy
          uses: appleboy/ssh-action@v1.2.2
          with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USER }}
            key: ${{ secrets.EC2_PRIVATE_KEY }}

            script: |
              cd /home/ubuntu/user-management-system
              docker pull prashantkumar1911/user-management-system:latest
              docker compose up -d