name: Test Workflow

on:
    push:
        branches:
            - dev

jobs:
    build:
        runs-on: ubuntu-latest

        steps:

            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Run Command
              run: npm ci

            - name: Docker Build
              run: |
                docker build \
                -t node-app:latest \
                -t node-app:${{ github.sha }} \
                .

            - name: Print Docker Images
              run: docker images
    
    deploy:
      needs: build
      runs-on: ubuntu-latest

      steps:

        - name: Configure SSH
          run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

        - name: Test SSH Connections
          run: |
            ssh ${{ secrets.EC2_PRIVATE_KEY }} ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "echo Connected!"